<?php

namespace App\Services;

class Locations
{
    public function getLocations()
    {
        // Crawled from kupujem prodajem
        return [
            "Beograd",
            "Niš",
            "Kuršumlija",
            "Inostranstvo",
            "Subotica",
            "Kraljevo",
            "Pirot",
            "Kragujevac",
            "Leskovac",
            "Vranje",
            "Jagodina",
            "Prokuplje",
            "Novi Sad",
            "Kruševac",
            "Čačak",
            "Šabac",
            "Smederevo",
            "Valjevo",
            "Užice",
            "Novi Pazar",
            "Požarevac",
            "Zaječar",
            "Bor",
            "Borča",
            "Smederevska Palanka",
            "Paraćin",
            "Aranđelovac",
            "Gornji Milanovac",
            "Lazarevac",
            "Obrenovac",
            "Grocka",
            "Mladenovac",
            "Loznica",
            "Ćuprija",
            "Priboj",
            "Zrenjanin",
            "Pančevo",
            "Sombor",
            "Kikinda",
            "Sremska Mitrovica",
            "Vršac",
            "Ruma",
            "Bačka Palanka",
            "Bečej",
            "Senta",
            "Kula",
            "Vrbas",
            "Inđija",
            "Apatin",
            "Temerin",
            "Kosovska Mitrovica",
            "Velika Plana",
            "Trstenik",
            "Zlatibor",
            "Vrnjačka Banja",
            "Kladovo",
            "Kučevo",
            "Šid",
            "Aleksinac",
            "Veliko Gradište",
            "Prijepolje",
            "Kanjiža",
            "Bela Crkva",
            "Požega",
            "Melenci",
            "Novi Bečej",
            "Svilajnac",
            "Ub",
            "Ada",
            "Kosjerić",
            "Sremska Kamenica",
            "Bačka Topola",
            "Brus",
            "Petrovac na Mlavi",
            "Stara Pazova",
            "Negotin",
            "Novi Kneževac",
            "Sremski Karlovci",
            "Bajina Bašta",
            "Odžaci",
            "Kovin",
            "Aleksandrovac",
            "Bela Palanka",
            "Mali Zvornik",
            "Ražanj",
            "Bujanovac",
            "Preševo",
            "Sokobanja",
            "Ivanjica",
            "Knjaževac",
            "Raška",
            "Vlasotince",
            "Tutin",
            "Sjenica",
            "Srbobran",
            "Blace",
            "Majdanpek",
            "Topola",
            "Beograd | Zemun",
            "Arilje",
            "Barajevo",
            "Beograd | Voždovac",
            "Beograd | Vračar",
            "Beograd | Zvezdara",
            "Beograd | Novi Bg.",
            "Beograd | Palilula",
            "Beograd | Rakovica",
            "Beograd | Savski venac",
            "Sopot",
            "Beograd | Stari grad",
            "Surčin",
            "Beograd | Čukarica",
            "Svrljig",
            "Dimitrovgrad",
            "Ljig",
            "Nova Pazova",
            "Titel",
            "Pukovac",
            "Vladičin Han",
            "Irig",
            "Kostolac",
            "Beočin",
            "Varvarin",
            "Ćićevac",
            "Futog",
            "Feketić",
            "Žabalj",
            "Surdulica",
            "Kopaonik",
            "Babušnica",
            "Bački Petrovac",
            "Mali Iđoš",
            "Bosilegrad",
            "Ljubovija",
            "Leposavić",
            "Lapovo",
            "Pojate",
            "Despotovac",
            "Nova Varoš",
            "Lebane",
            "Vinča",
            "Bač",
            "Batočina",
            "Plandište",
            "Bogatić",
            "Knić",
            "Beograd | Batajnica",
            "Azanja",
            "Čelarevo",
            "Novi Banovci",
            "Kovačica",
            "Beška",
            "Sevojno",
            "Petrovaradin",
            "Lučani",
            "Kać",
            "Kovilj",
            "Alibunar",
            "Veternik",
            "Čurug",
            "Kačarevo",
            "Kusadak",
            "Koceljeva",
            "Ruski Krstur",
            "Mol",
            "Banatsko Novo Selo",
            "Doljevac",
            "Crvenka",
            "Bačko Petrovo Selo",
            "Sivac",
            "Banatski Karlovac",
            "Rumenka",
            "Bojnik",
            "Lajkovac",
            "Dolovo (kod Pančeva)",
            "Opovo",
            "Palić",
            "Vladimirci",
            "Žagubica",
            "Žitorađa",
            "Boljevac",
            "Starčevo",
            "Banja Koviljača",
            "Zvečan",
            "Zubin Potok",
            "Merošina",
            "Rača Kragujevačka",
            "Štrpce",
            "Stari Banovci",
            "Krupanj",
            "Čoka",
            "Vojka",
            "Vranjska Banja",
            "Horgoš",
            "Medveđa",
            "Mionica",
            "Omoljica",
            "Golubinci",
            "Debeljača",
            "Jakovo",
            "Golubac",
            "Vrdnik",
            "Pećinci",
            "Padina",
            "Šimanovci",
            "Hrvatska (HR)",
            "Slovenija",
            "Crna Gora (CG)",
            "Severna Makedonija (RSM)",
            "Bosna i Hercegovina (BiH)",
            "Bavanište",
            "Gadžin Han",
            "Kosmaj",
            "Divčibare",
            "Banja Vrujci",
            "Jošanička Banja",
            "Lukovska Banja",
            "Mataruška Banja",
            "Niška Banja",
            "Prolom Banja",
            "Banja Rusanda",
            "Vladimirovac",
            "Vrčin",
            "Laćarak",
            "Bajmok",
            "Beograd | Ugrinovci",
            "Kisač",
            "Majur (Šabac)",
            "Banatski Brestovac",
            "RSM | Ohrid",
            "Priština",
            "Prizren",
            "Gnjilane",
            "Peć",
            "Uroševac",
            "Đakovica",
            "Podujevo",
            "Vučitrn",
            "Crepaja",
            "Dobanovci",
            "RSM | Skopje",
            "RSM | Kumanovo",
            "RSM | Tetovo",
            "RSM | Bitola",
            "RSM | Štip",
            "RSM | Gostivar",
            "RSM | Prilep",
            "RSM | Veles",
            "RSM | Strumica",
            "RSM | Kavadarci",
            "RSM | Kočani",
            "RSM | Kičevo",
            "CG | Bijelo Polje",
            "CG | Pljevlja",
            "CG | Berane",
            "CG | Podgorica",
            "CG | Nikšić",
            "CG | Bar",
            "CG | Herceg Novi",
            "CG | Budva",
            "CG | Tivat",
            "CG | Žabljak",
            "CG | Cetinje",
            "CG | Kotor",
            "BiH | Tuzla",
            "BiH | Mostar",
            "BiH | Banja Luka",
            "BiH | Sarajevo",
            "BiH | Trebinje",
            "BiH | Višegrad",
            "BiH | Zenica",
            "BiH | Bijeljina",
            "BiH | Zvornik",
            "BiH | Prnjavor",
            "BiH | Modriča",
            "BiH | Prijedor",
            "BiH | Foča",
            "BiH | Brčko",
            "BiH | Goražde",
            "BiH | Derventa",
            "BiH | Doboj",
            "BiH | Bihać",
            "BiH | Kiseljak",
            "BiH | Srebrenik",
            "BiH | Bugojno",
            "BiH | Travnik",
            "BiH | Sanski Most",
            "BiH | Bosanska Krupa",
            "HR | Osijek",
            "HR | Rijeka",
            "HR | Zagreb",
            "HR | Pula",
            "HR | Vukovar",
            "HR | Split",
            "HR | Dubrovnik",
            "HR | Varaždin",
            "HR | Šibenik",
            "HR | Karlovac",
            "HR | Zadar",
            "HR | Slavonski Brod",
            "BiH | Bratunac",
            "Donji Milanovac",
            "Bačko Gradište",
            "Osečina",
            "Šajkaš",
            "Lozovik (Velika Plana)",
            "Rekovac",
            "Sirig",
            "Srpska Crnja",
            "Novo Miloševo",
            "CG | Rožaje",
            "Žitište",
            "Sečanj",
            "Nova Crnja",
            "Malo Crniće",
            "Trgovište",
            "Čajetina",
            "Žabari",
            "Guča"
        ];
    }
}
