server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;

    index index.php index.html;

    charset utf-8;

    # Set Max Upload Size
    client_max_body_size 10M;

    # Laravel's standard routing structure
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Pass PHP requests to the FPM service (named 'app' in docker-compose.yml)
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Deny access to .htaccess files and internal folders
    location ~ /\.ht {
        deny all;
    }


}