[supervisord]
nodaemon=true

[supervisorctl]

[inet_http_server]
port = 127.0.0.1:9001

[program:your_process]
command=php /var/www/html/artisan queue:work --max-jobs=1000
stdout_logfile=/dev/stdout        ; Directs standard output to the container's stdout
stdout_logfile_maxbytes=0         ; Prevents log rotation
stderr_logfile=/dev/stderr        ; Directs standard error to the container's stderr
stderr_logfile_maxbytes=0         ; Prevents log rotation
redirect_stderr=true              ; Combines stdout and stderr into a single log stream
autostart=true                    ; Starts the process automatically when supervisord starts
autorestart=true
